### ISSUE TITLE
Comandos em PostgreSQL

### ISSUE THREAD

**Issue by degrecci** [victorperin/LPBD-trabalho#1]
CREATE TABLE IF NOT EXISTS Albuns (
  Id SERIAL NOT NULL,
  Nome varchar(50) NOT NULL,
  AnoLancamento int NOT NULL,
  PRIMARY KEY (Id)
);

**Comment by victorperin** [comment]
:+1:

**Comment by victorperin** [comment]
Fixed! thanks!
