### ISSUE TITLE
fix enum to boolean

### ISSUE THREAD

**Issue by degrecci** [victorperin/LPBD-trabalho#2]
CREATE TABLE IF NOT EXISTS AlbunsArtistas (
  ArtistaId int NOT NULL,
  AlbumId int NOT NULL,
  Principal BOOLEAN NOT NULL,
  PRIMARY KEY (ArtistaId,AlbumId),
  CONSTRAINT album_AlbunsArtistas FOREIGN KEY (AlbumId) REFERENCES Albuns (Id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT artista_AlbunsArtistas FOREIGN KEY (ArtistaId) REFERENCES Artistas (Id) ON DELETE CASCADE ON UPDATE CASCADE
);

**Comment by victorperin** [comment]
:+1: 
fixed, thanks!
